version: '3.7'
volumes:
  volMysql:
services:
  dbMysql:
    image: mysql:latest
    container_name: 'mysqlito2'
    environment:
      - MYSQL_ROOT_PASSWORD=basesecreta
      - MYSQL_DATABASE=unatiendita
    ports:
      - 3307:3306
    volumes:
      - volMysql:/var/lib/mysql

